#ifndef STYLE_H_
#define STYLE_H_

#define BACKGROUND_COLOR 0x000000FF
#define GRID_COLOR 0xFFFFFFFF
#define WALL_COLOR (GRID_COLOR)
#define FOOD_COLOR 0x9067C6FF
#define AGENT_COLOR 0xFF499EFF

#endif // STYLE_H_
